kind: pipeline
name: check-app-compatbility

steps:
  - name: check-app-compatbility
    image: nextcloudci/php7.0:php7.0-2
    environment:
      APP_NAME: data_request
      CORE_BRANCH: stable15
      DB: sqlite
    commands:
        # Pre-setup steps
        - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
        - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
        - cd ../server

        # Code checker
        - ./occ app:check-code $APP_NAME

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: syntax-php7.0

steps:
  - name: syntax-php7.0
    image: nextcloudci/php7.0:php7.0-2
    environment:
      APP_NAME: data_request
      CORE_BRANCH: stable15
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - composer install
      - ./lib/composer/bin/parallel-lint apps/$APP_NAME/

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php7.0

steps:
  - name: php7.0
    image: nextcloudci/php7.0:php7.0-2
    environment:
      APP_NAME: data_request
      CORE_BRANCH: stable15
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php7.1

steps:
  - name: php7.1
    image: nextcloudci/php7.1:php7.1-15
    environment:
      APP_NAME: data_request
      CORE_BRANCH: stable15
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php7.2

steps:
  - name: php7.2
    image: nextcloudci/php7.2:php7.2-12
    environment:
      APP_NAME: data_request
      CORE_BRANCH: stable15
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
